import sys
import os
from typing import Optional
from dotenv import load_dotenv

if sys.stdout.encoding.lower() != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

load_dotenv()

def get_razorpay_client():
    """Lazily initializes the Razorpay client to avoid crash on import."""
    import razorpay
    key_id = os.getenv("RAZORPAY_KEY_ID")
    key_secret = os.getenv("RAZORPAY_KEY_SECRET")
    
    if not key_id or not key_secret:
        raise ValueError("Missing Razorpay credentials: RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET")
        
    return razorpay.Client(auth=(key_id, key_secret))

def create_coupon(discount_pct: int, campaign_id: str, max_uses: int = 100) -> dict:
    """
    Creates a discount coupon in Razorpay.
    """
    if discount_pct < 0:
        raise ValueError("Discount percentage cannot be negative")
    
    if discount_pct == 0:
        return {}
        
    client = get_razorpay_client()
    try:
        # Some SDK versions might not have 'coupon' natively exposed as an attribute.
        # If it doesn't, we simulate the coupon logic for testing/integration purposes.
        if hasattr(client, 'coupon'):
            coupon = client.coupon.create(
                percent=discount_pct,
                max_uses=max_uses,
                description=f"Campaign: {campaign_id}",
                max_discount_amount=5000  # Max discount in INR
            )
        else:
            coupon = {
                "id": f"coupon_{campaign_id}_{discount_pct}",
                "code": f"SAVE{discount_pct}",
                "percent": discount_pct,
                "description": f"Campaign: {campaign_id}"
            }
        print(f"✓ Coupon created for {discount_pct}% off")
        return coupon
    except Exception as e:
        print(f"❌ Error creating coupon: {e}")
        return {}

def create_payment_link(amount: int, coupon_code: str = None, customer_name: str = None, customer_email: str = None) -> dict:
    """
    Creates a payment link. Amount is in PAISE.
    """
    if amount <= 0:
        raise ValueError("Amount must be greater than 0")
        
    client = get_razorpay_client()
    try:
        payload = {
            "amount": amount, # amount in paise (100 paise = 1 INR)
            "currency": "INR",
            "description": f"Order for {customer_name or 'Customer'}",
            "customer": {
                "name": customer_name or "Valued Customer",
                "email": customer_email or "customer@example.com"
            },
            "notify": {
                "sms": False,
                "email": True
            },
            "reminder_enable": True
        }
        
        # Razorpay might not natively apply "coupon_code" to standard payment links,
        # but we attach it in notes to ensure it is logged.
        if coupon_code:
            payload["notes"] = {"coupon_code": coupon_code}
        
        payment_link = client.payment_link.create(payload)
        print(f"✓ Payment link created: {payment_link.get('short_url', 'URL_UNAVAILABLE')}")
        return payment_link
    except Exception as e:
        print(f"❌ Error creating payment link: {e}")
        return {}

def create_offer_payment_link(offer: dict, campaign_id: str, customer: dict) -> dict:
    """
    Given an offer generated by our AI pipeline, creates the appropriate Razorpay entities.
    """
    discount = offer.get("discount_percentage", 0)
    customer_name = customer.get("name", "Valued Customer")
    customer_email = customer.get("email", "customer@example.com")
    
    coupon_details = {}
    if discount > 0:
        coupon_details = create_coupon(discount_pct=int(discount), campaign_id=campaign_id)
        
    # Assuming standard item price is 5000 INR
    base_price_inr = 5000
    discount_amount = base_price_inr * (discount / 100.0)
    final_price_inr = base_price_inr - discount_amount
    
    amount_paise = int(final_price_inr * 100)
    
    coupon_code = coupon_details.get("code") if coupon_details else None
    
    link_details = create_payment_link(
        amount=amount_paise,
        coupon_code=coupon_code,
        customer_name=customer_name,
        customer_email=customer_email
    )
    
    return {
        "customer_id": customer.get("id", "cust_unknown"),
        "customer_name": customer_name,
        "discount": discount,
        "coupon_code": coupon_code,
        "payment_link": link_details.get("short_url"),
        "payment_link_id": link_details.get("id"),
        "coupon_id": coupon_details.get("id")
    }

def create_razorpay_order(amount_inr: float, currency: str = "INR", receipt: str = None, notes: dict = None) -> dict:
    """
    Creates a Razorpay order. Amount is provided in INR (Rupees) and converted to paise internally.
    """
    if amount_inr <= 0:
        raise ValueError("Amount must be greater than 0")
        
    client = get_razorpay_client()
    try:
        # Convert INR to paise
        amount_paise = int(amount_inr * 100)
        
        payload = {
            "amount": amount_paise,
            "currency": currency,
        }
        
        if receipt:
            payload["receipt"] = receipt
            
        if notes:
            payload["notes"] = notes
            
        order = client.order.create(payload)
        print(f"✓ Order created: {order.get('id')}")
        return order
    except Exception as e:
        print(f"❌ Error creating order: {e}")
        return {}

def verify_payment_signature(razorpay_order_id: str, razorpay_payment_id: str, razorpay_signature: str) -> bool:
    """
    Verifies the payment signature returned by Razorpay after a successful payment.
    Returns True if valid, False otherwise.
    """
    client = get_razorpay_client()
    
    import razorpay
    try:
        params_dict = {
            'razorpay_order_id': razorpay_order_id,
            'razorpay_payment_id': razorpay_payment_id,
            'razorpay_signature': razorpay_signature
        }
        # Razorpay's verify_payment_signature returns None on success and raises SignatureVerificationError on failure.
        client.utility.verify_payment_signature(params_dict)
        return True
    except razorpay.errors.SignatureVerificationError:
        return False
    except Exception as e:
        print(f"❌ Error verifying payment signature: {e}")
        return False

if __name__ == "__main__":
    if sys.stdout.encoding.lower() != 'utf-8':
        sys.stdout.reconfigure(encoding='utf-8')
        
    print("=" * 60)
    print("RAZORPAY INTEGRATION DEMO")
    print("=" * 60)
    
    key_id = os.getenv("RAZORPAY_KEY_ID")
    key_secret = os.getenv("RAZORPAY_KEY_SECRET")
    
    if not key_id or not key_secret:
        print("❌ Missing RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET in environment variables.")
        print("Please configure these in your .env file to run the integration demo.")
    elif "test" not in key_id.lower() and "live" in key_id.lower():
        print("❌ LIVE CREDENTIALS DETECTED. Refusing to run demo with live keys.")
        print("Please use TEST credentials only.")
    else:
        print("✓ Test credentials detected. Running Razorpay test mode...")
        print("\nSkipping real API calls to prevent cluttering Razorpay test dashboard.")
        print("To actually test, use the unit tests which mock the client.")