'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

export default function CreateCampaign() {
  const [goal, setGoal] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const router = useRouter()

  const handleCreateCampaign = async (e) => {
    e.preventDefault()
    setLoading(true)
    setError('')

    const merchantId = localStorage.getItem('merchantId')

    try {
      // Call backend to create campaign
      const response = await fetch('http://localhost:8000/campaign/create', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          merchant_id: merchantId,
          goal: goal,
          target_segments: ['loyal', 'new_visitor', 'cart_abandoned', 'high_value', 'price_sensitive']
        }),
      })

      const data = await response.json()

      if (response.ok) {
        setResult(data)
      } else {
        setError(data.detail || 'Failed to create campaign')
      }
    } catch (error) {
      setError('Error: ' + error.message)
    }

    setLoading(false)
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Back Button */}
      <div className="bg-white border-b p-4">
        <Link href="/dashboard" className="text-blue-600 hover:text-blue-800 font-semibold">
          ← Back to Dashboard
        </Link>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto p-8">
        <h1 className="text-3xl font-bold mb-2 text-gray-800">🚀 Create Campaign</h1>
        <p className="text-gray-600 mb-8">
          Set a goal and let AI create a personalized campaign to achieve it.
        </p>

        {/* Form */}
        <form onSubmit={handleCreateCampaign} className="bg-white p-8 rounded-lg shadow-lg mb-8">
          <div className="mb-6">
            <label className="block text-lg font-semibold text-gray-800 mb-2">
              What's your goal?
            </label>
            <textarea
              placeholder="e.g., Increase summer collection sales by 20% this week"
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 h-32 resize-none"
              required
            />
            <p className="text-gray-500 text-sm mt-2">
              Be specific about what you want to achieve and by when.
            </p>
          </div>

          {/* Error */}
          {error && (
            <div className="p-4 bg-red-100 border border-red-400 text-red-700 rounded-lg mb-6">
              {error}
            </div>
          )}

          {/* Button */}
          <button
            type="submit"
            disabled={loading || !goal.trim()}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-lg transition disabled:opacity-50"
          >
            {loading ? '⏳ Creating Campaign...' : '✨ Create Campaign'}
          </button>
        </form>

        {/* Results */}
        {result && (
          <div className="bg-green-50 border-2 border-green-400 p-8 rounded-lg">
            <h2 className="text-2xl font-bold text-green-800 mb-4">✅ Campaign Created Successfully!</h2>

            <div className="mb-6 bg-white p-4 rounded-lg">
              <p className="text-gray-700 mb-2">
                <strong>Campaign ID:</strong> {result.campaign_id}
              </p>
              <p className="text-gray-700 mb-2">
                <strong>Goal:</strong> {result.goal}
              </p>
              <p className="text-gray-700">
                <strong>Customers Targeted:</strong> {result.total_customers}
              </p>
            </div>

            <h3 className="text-xl font-bold text-gray-800 mb-4">Offers Generated by AI:</h3>

            <div className="space-y-4 mb-8">
              {Object.entries(result.offers).map(([segment, offer]) => (
                <div key={segment} className="bg-white p-4 rounded-lg border border-gray-200">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="font-bold text-gray-800 capitalize">
                      {segment.replace(/_/g, ' ')}
                    </h4>
                    <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-semibold">
                      {offer.discount_pct}% off
                    </span>
                  </div>
                  <p className="text-gray-700 mb-2">
                    <strong>Offer:</strong> {offer.offer}
                  </p>
                  <p className="text-gray-600 text-sm">
                    <strong>Reasoning:</strong> {offer.reasoning}
                  </p>
                </div>
              ))}
            </div>

            <div className="bg-white p-4 rounded-lg border border-gray-200 mb-8">
              <h3 className="font-bold text-gray-800 mb-3">Payment Links Generated:</h3>
              <p className="text-gray-600 text-sm mb-4">
                {result.campaign_links.length} unique payment links created for customers.
              </p>
              <button
                onClick={() => alert('View in monitor dashboard')}
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded font-semibold"
              >
                View in Monitor Dashboard
              </button>
            </div>

            <button
              onClick={() => {
                setGoal('')
                setResult(null)
              }}
              className="w-full bg-gray-600 hover:bg-gray-700 text-white font-bold py-2 rounded-lg transition"
            >
              Create Another Campaign
            </button>
          </div>
        )}
      </div>
    </div>
  )
}